# Generated by Django 3.0.8 on 2020-08-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='게시판 이름')),
                ('write_permission', models.BooleanField(default=False, verbose_name='쓰기 권한')),
                ('read_permission', models.BooleanField(default=True, verbose_name='열람 권한')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000, verbose_name='쪽지 내용')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='보낸 날짜')),
                ('receive_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
                ('send_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Message', verbose_name='보낸 사람')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='게시물 제목')),
                ('content', models.TextField(max_length=500, verbose_name='게시물 내용')),
                ('m_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('write_permission', models.BooleanField(default=False, verbose_name='쓰기 권한')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='게시판')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('read_permission', models.BooleanField(default=True, verbose_name='열람 권한')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓글 소유자')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Document', verbose_name='게시물 대상')),
                ('re_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Comment', verbose_name='대댓글 대상')),
            ],
        ),
    ]
