# Generated by Django 3.0.8 on 2020-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='이름')),
                ('user_id', models.CharField(max_length=15, verbose_name='아이디')),
                ('user_password', models.CharField(max_length=15, verbose_name='비밀번호')),
                ('user_birth', models.DateField(verbose_name='생년월일')),
                ('user_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('user_style', models.CharField(max_length=15, verbose_name='회비 납부 여부')),
                ('user_thumbnail', models.FilePathField(null=True, verbose_name='프로필 사진')),
                ('user_grade', models.CharField(default='beginner', max_length=10, verbose_name='등급')),
                ('user_gender', models.CharField(max_length=20, verbose_name='성별')),
            ],
        ),
    ]
